# Site settings
title: Inform
email: michael.guida@colorado.edu
description:
baseurl: "/sensor-shirt" # the subpath of your site, e.g. /blog/
url: "http://mguida22.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
